services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"

  web-dev:
    build:
      context: ./app
    command: flask run --host=0.0.0.0 --port=5000 --reload
    volumes:
      - ./app:/app
    ports:
      - "5001:5000"
      - "4444:4444"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      FLASK_APP: /app/app.py
      JWT_SECRET_KEY: secret_key
      DATABASE_URL: mysql+pymysql://root:password@db/flaskdb

  auth_service:
    build:
      context: ./gg-auth
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5002:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: sqlite:///auth.db
      JWT_SECRET_KEY: secret_key
    volumes:
      - ./gg-auth:/app

  plant_service:
    build:
      context: ./gg-plant
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5003:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: sqlite:///plant.db
    volumes:
      - ./gg-plant:/app

  notification_service:
    build:
      context: ./gg-notification
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5004:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./gg-notification:/app

  statistics_service:
    build:
      context: ./gg-statistics
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5005:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./gg-statistics:/app