services:
  gg-dev:
    build:
      context: ./app
    command: flask run --host=0.0.0.0 --port=5000 --reload
    volumes:
      - ./app:/app
    ports:
      - "5001:5000"
      - "4444:4444"
    environment:
      FLASK_ENV: development
      FLASK_APP: /app/app.py
      JWT_SECRET_KEY: secret_key

  auth_service:
    build:
      context: ./gg-auth
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5002:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: sqlite:///auth.db
      JWT_SECRET_KEY: secret_key
    volumes:
      - ./gg-auth:/app

  plant_service:
    build:
      context: ./gg-plant
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5003:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: sqlite:///plant.db
    volumes:
      - ./gg-plant:/app

  notification_service:
    build:
      context: ./gg-notification
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5004:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./gg-notification:/app

  statistics_service:
    build:
      context: ./gg-statistics
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5005:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./gg-statistics:/app

  greeting_service:
    build:
      context: ./greeting
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5006:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: MA_greeting.py
    volumes:
      - ./greeting:/app
